services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/SassyJack/SistemaDeGestionSMDS
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:kUIrA7aYEsf6ktP23YqrwtcQnLLxm/MhHhhpVPd2dWM=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://sistemadegestionsmds.onrender.com

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0h55m0d13ps73cincd0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: sdgsanmigueldesema
      - key: DB_USERNAME
        value: sdgsanmigueldesema_user
      - key: DB_PASSWORD
        value: LIlnbSPIgyPPTQpuLTXAgHWdqluMTnre

      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120

      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

      - key: VITE_APP_NAME
        value: Laravel
